inherit_gem:
  rubocop-rails:
    - config/rails.yml

AllCops:
  TargetRubyVersion: 2.4
  Include:
    - Gemfile
    - '**/Gemfile'
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - '**/templates/**/*'
    - '**/vendor/**/*'

Rails:
  Enabled: true

# Disable block length for RSpec tests
Metrics/BlockLength:
  Exclude:
    - 'config/environments/**/*'
    - 'spec/**/*'

# Disable Class definitions warnings using ::
Style/ClassAndModuleChildren:
  Enabled: false

# Disable Missing top-level class documentation comment.
Style/Documentation:
  Enabled: false

# Disable include used at top level.
Style/MixinUsage:
  Enabled: false
